export const GET_LIST = 'GET_LIST'

export const GET_LIST_REQUEST = 'GET_LIST_REQUEST'
export const GET_LIST_SUCCESS = 'GET_LIST_SUCCESS'
export const GET_LIST_FAILURE = 'GET_LIST_FAILURE'

export const SET_CODE = 'SET_CODE'

export const INIT_CATEGORY = 'INIT_CATEGORY'
